version: '3.8'

services:
  receivables-api-dev:
    build: 
      context: .
      dockerfile: ./Invoicing.Receivables.API/Dockerfile
    image: receivables-api-dev
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ReceivablesDB=Host=receivables-db-dev;Port=5432;Database=YourDatabaseName;Username=YourUsername;Password=YourPassword;
      - Password=YourPassword
    depends_on:
      - receivables-db-dev
    networks:
      - receivables-network-dev-external
    command: ["./wait-for-postgres.sh", "receivables-db-dev:5432", "--", "echo",  "Database is UP"]

  receivables-db-dev:
    image: postgres:16.1
    container_name: receivables-db-dev
    environment:
      POSTGRES_DB: YourDatabaseName
      POSTGRES_USER: YourUsername
      POSTGRES_PASSWORD: YourPassword
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/Development/ReceivablesDb:/var/lib/postgresql/data
    networks:
      - receivables-network-dev-external

networks:
  receivables-network-dev-external:
    driver: bridge
