version: '3.8'

services:
  identity-db-system-tests:
    image: postgres:16.1
    container_name: identity-db_system-tests
    environment:
      POSTGRES_DB: YourDatabaseName
      POSTGRES_USER: YourUsername
      POSTGRES_PASSWORD: YourPassword
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/SystemTests/IdentityDb:/var/lib/postgresql/data
    networks:
      - identity-network-system-tests-external
      
#  identity-tests-system-tests:
#    container_name: identity-tests_system-tests
#    build:
#      context: .
#      dockerfile: ./Invoicing.Identity.Tests/Dockerfile
#    image: identity-tests:system-tests
#    working_dir: /app
#    environment:
#      - ASPNETCORE_ENVIRONMENT=SystemTests
#      - ConnectionStrings__IdentityDB=Host=identity-db-system-tests;Port=5433;Database=YourDatabaseName;Username=YourUsername;Password=YourPassword;
#    depends_on:
#      - identity-db-system-tests
#    networks:
#      - identity-network-external

networks:
  identity-network-system-tests-external:
    driver: bridge
